### ISSUE TITLE
Heterogeneous vertices?

### ISSUE THREAD

**Issue by cricket007** [graphframes/graphframes#111]
```
val v = sqlContext.createDataFrame(List(
  ("a", "Alice", 34),
  ("b", "Bob", 36),
  ("c", "Charlie", 30)
)).toDF("id", "name", "age")
```

What if I wanted to say, for example, that these people work at a company? Say we didn't care about the "age" of the company, just who the employees are. 

So how would this data be added as a Vertex, or is it even possible?

```
("companyA", "Foobar, Inc.")
```

The edge is straightforward 

```
("a", "companyA", "works_at")
```

---

To clarify, this isn't possible because the Company has no "age", so the schema can't be applied

```
val v = sqlContext.createDataFrame(List(
  ("a", "Alice", 34),
  ("b", "Bob", 36),
  ("c", "Charlie", 30),
  ("companyA", "FooBar, Inc.")
)).toDF("id", "name", "age")
```

**Comment by lewisc** [comment]
This isn't a graphframes problem, it's a dataframes general issue.

To get rid of the age you can use:
`v.drop(col("age"))`

To add the new information you would (in traditional sql style), add the information as a new column,

Assuming each employee is going to work for the same company
`v.withColumn("companyA", lit("Foobar, Inc"))`

I hope this helps.

**Comment by cricket007** [comment]
I understand it's a DataFrame problem. So, I want the age of the People, just not the Company. For example, I'm concerned about this. 

```
.toDF("id", "name", "age")
```

How can I add a vertex within the `List` that does not match that schema, or differs completely?

**Comment by lewisc** [comment]
As far as I know, you can't (exactly) have different "types" of vertices in networkx parlance. What you could do is have a very wide schema (basically the 2 schemas unioned), and then only fill in the relevant pieces.

**Comment by felixcheung** [comment]
I might be missing something, can't you do
```
val v = spark.createDataFrame(List(
  ("a", "Alice", Some(34)),
  ("b", "Bob", Some(36)),
  ("c", "Charlie", Some(30)),
  ("companyA", "FooBar, Inc.", None)
)).toDF("id", "name", "age")
```

you get
```
v.printSchema
root
 |-- id: string (nullable = true)
 |-- name: string (nullable = true)
 |-- age: integer (nullable = true)
```

**Comment by thunterdb** [comment]
As the others have pointed out, Spark has limited support for disjunctions (sum types in algebraic parlance), save for the nullable types. One solution if you want to encode such types is to use different structures and make a union of them using options. In your example, you could use the following data type:

```scala
case class Person(name: String, age: Int)
case class Company(companyName: String)

case class VertexType(
  id: String, //  all vertices need an id, so it makes sense to pull it at the top
  person: Option[Person],
  company: Option[Company]
)
```
You can then project the data to only persons or companies using http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.DataFrameNaFunctions

Since this is a limitation that is intrinsic to Spark, there is not much that we can do about it. I am going to close the ticket for now.

**Comment by cricket007** [comment]
Thanks all. I'm no longer working on that project, so my memory of what I was ultimately trying to accomplish has faded. Essentially, I was comparing the capabilities & performance of actual graph databases such as Neo4j & OrientDB to that of Spark+GraphFrames without using the Spark connectors and just parsing data out of CSV files, if that makes sense.
