### ISSUE TITLE
SLF4J Logging Error

### ISSUE THREAD

**Issue by michaelqiu94** [graphframes/graphframes#114]
Hi,
    I tried creating a graph frame, but it gave me this ClassDefNotFound error:

java.lang.NoClassDefFoundError: com/typesafe/scalalogging/slf4j/LazyLogging

I am using GraphFrames 0.2.0 for Spark 2.0 and Scala 2.11. Any ideas what could be causing this? Thanks!

**Comment by nchammas** [comment]
Dup of #113?
