### ISSUE TITLE
Connected Components: improve unit tests

### ISSUE THREAD

**Issue by jkbradley** [graphframes/graphframes#121]
We should improve unit test coverage for CC before we release the new version.

**Comment by mavencode01** [comment]
@mengxr I'm experiencing an issue with  connected component, basically I'm trying to cluster a hierarchical dataset. It works fine for small dataset, I could clustered the data into separate clusters. 

However, for large hierarchical dataset (about `1.60million vertices`) the result seems wrong. 
The resulting clusters from connected component have many intersections. This should not be the case. I expect the hierarchical dataset to be clustered into separate smaller clusters.

    ...
    val vertices = universe.map(u => (u.id, u.username, u.age, u.gamescore))
                              .toDF("id", "username", "age","gamescore")
                              .alias("v")


    val lookup = sparkSession.sparkContext.broadcast(universe.rdd.collectAsMap())


    def buildEdges(src: String, dest: String) = {
        Edge(lookup.value.get(src).get, lookup.value.get(dest).get, 0)
    }


    val edges  =  similarityDatasetNoJboss.mapPartitions(_.map(s => buildEdges(s.username1, s.username2)))
                                          .toDF("src", "dst", "default")

    val graph = GraphFrame(vertices, edges)

    val cc = graph.connectedComponents.run().select("id", "component")


Do some validation test

    Select id, count(component)
    group by id

I expect each id to belong to one cluster/component and count = 1

**Comment by jkbradley** [comment]
@mavencode01 Do you know if your ```vertices``` DataFrame has multiple rows with the same ID?  If so, that might cause the bug you're seeing.  GraphFrames assumes that the vertices DataFrame is valid and does not verify or dedup.

**Comment by mengxr** [comment]
@mavencode01 please create a new issue to continue the discussion. This one is only for adding new unit tests. I'm going to mark it as closed. Thanks!
