### ISSUE TITLE
Graphframe connected component bug

### ISSUE THREAD

**Issue by mavencode01** [graphframes/graphframes#134]
Moving the issue here, 
I'm trying to cluster a hierarchical dataset. This works fine for small dataset, I could cluster the data into separate clusters.

However, for large hierarchical dataset (about 1.60million vertices) the result seems wrong. 
The resulting clusters from connected component have many intersections. This should not be the case. I expect the hierarchical dataset to be clustered into separate smaller clusters.

	...
	val vertices = universe.map(u => (u.id, u.username, u.age, u.gamescore))
	                          .toDF("id", "username", "age","gamescore")
	                          .alias("v")

	val lookup = sparkSession.sparkContext.broadcast(universeMap.rdd.collectAsMap())

	def buildEdges(src: String, dest: String) = {
	    Edge(lookup.value.get(src).get, lookup.value.get(dest).get, 0)
	}

	val edges  =  similarityDatasetNoJboss.mapPartitions(_.map(s => buildEdges(s.username1, s.username2)))
	                                      .toDF("src", "dst", "default")

	val graph = GraphFrame(vertices, edges)

	val cc = graph.connectedComponents.run().select("id", "component")
Do some validation test

    Select id, count(component) 
    group by id

I expect each `id `to belong to one cluster/component and count = 1 instead id belong to multiple clusters/component.

**Comment by thunterdb** [comment]
@mavencode01 do you have a dataset and a full example that reproduces the issue you are seeing?

**Comment by mengxr** [comment]
@mavencode01 Please also let us know whether you are using the DataFrame-based implementation in current master or the GraphX implementation in release 0.2.

**Comment by mavencode01** [comment]
@mengxr @thunterdb - I think it's my bug, I got duplicate Ids in my vertices. Thanks for pointing it out @mengxr
