### ISSUE TITLE
Make graphx to graphframe converters public

### ISSUE THREAD

**Issue by lewisc** [graphframes/graphframes#149]
The graphx to graphframe (and vice versa) conversion logic is hidden behind a private tag. Is there a specific reason for this or could these be made public?

I would be willing to make the changes (and also possibly add some tests to cover the code?) if that's acceptably by the project.

**Comment by felixcheung** [comment]
toGraphX is public and documented: http://graphframes.github.io/api/scala/index.html#org.graphframes.GraphFrame@toGraphX:org.apache.spark.graphx.Graph[org.apache.spark.sql.Row,org.apache.spark.sql.Row]

fromGraphX is not but I think it's just documentation.

**Comment by thunterdb** [comment]
I am closing this ticket, since it is documented.
