### ISSUE TITLE
GraphFrames package for Spark 2.1

### ISSUE THREAD

**Issue by nchammas** [graphframes/graphframes#157]
Is it safe/correct to use the GraphFrames package built for Spark 2.0 with Spark 2.1?

If not, I guess consider this issue a placeholder for creating a GraphFrames package built for Spark 2.1.

**Comment by felixcheung** [comment]
please see #153

**Comment by felixcheung** [comment]
Belief Propagation example does not work with Spark 2.1 without changes.

**Comment by thunterdb** [comment]
I have not checked BP, do you have an example that breaks it?

**Comment by felixcheung** [comment]
That was fixed in my PR that you merged. You should be good - except for the codegen issue

**Comment by geoHeil** [comment]
I just ran `build/sbt -Dspark.version=2.1.0 -Dscala.version=2.11.8 spDist assembly test` which worked without any test failures.

However a `sbt publishLocal` will publish to `.ivy2/local/default/graphframes_2.11/0.4.0-SNAPSHOT-spark2.1/` Why is the default included? How should it be published correctly?

**Comment by jkbradley** [comment]
I'm going to see about creating a release for 0.4.0 with versions for spark 2.0 and 2.1

**Comment by jkbradley** [comment]
Query: I'm thinking about dropping support for Spark 1.6 (1 1/4 years old).  Any protests?

**Comment by jkbradley** [comment]
I'm still working on prepping updated docs, but I'll send a PR soon

**Comment by felixcheung** [comment]
most of hadoop distro out there are still going as preview for Spark 2.x, or just starting to support 2.x within the last month or 2, so perhaps it makes sense to keep 1.x support for a bit longer.

**Comment by jkbradley** [comment]
Fair enough.  I won't remove support yet in case we make major changes to GraphFrames in the near future.

**Comment by jkbradley** [comment]
I forgot to close this issue before.  Closing now.
