### ISSUE TITLE
Add BeliefPropagation Example to Python

### ISSUE THREAD

**Issue by hughchristensen** [graphframes/graphframes#170]
https://github.com/graphframes/graphframes/issues/57 is now in review. 

This ticket is to add BeliefPropagation API to Python

* https://github.com/graphframes/graphframes/blob/master/src/main/scala/org/graphframes/examples/BeliefPropagation.scala

Myself and @tsivula will be working on this.

@thunterdb @jkbradley @qingpeng @mengxr @felixcheung Does anyone have any helpful input/ experiences here? Thank you.

**Comment by felixcheung** [comment]
That's an example though, not an API strictly speaking.

If we have aggregateMessages in Python we should be able to implement
runBPwithGraphFrames
In Python
