### ISSUE TITLE
GraphFrame solely from edge DataFrame

### ISSUE THREAD

**Issue by mtoto** [graphframes/graphframes#171]
According to the documentation: 

_"A GraphFrame can also be constructed from a single DataFrame containing edge information. The vertices will be inferred from the sources and destinations of the edges."_

Is this correct and if so how can this be achieved?

**Comment by dlawre14** [comment]
Did you ever figure out how to do this?

**Comment by felixcheung** [comment]
have you checked out the `fromEdges` API
https://github.com/graphframes/graphframes/blob/master/src/main/scala/org/graphframes/GraphFrame.scala#L618

http://graphframes.github.io/api/scala/index.html#org.graphframes.GraphFrame$
