### ISSUE TITLE
Remove Apache Spark 1.6 support

### ISSUE THREAD

**Issue by jkbradley** [graphframes/graphframes#193]
I'd like to remove 1.6 support
* I have not heard any complaints about not publishing a 1.6 version of the latest GraphFrames release.
* It is causing complications for https://github.com/graphframes/graphframes/issues/159  (where tests are suddenly much slower, though I'm not sure why yet).
* Later version of Spark are consistently better for GraphFrames b/c of DataFrame performance improvements

**Comment by jkbradley** [comment]
CC @nchammas @felixcheung  Does this sound OK to you?

**Comment by nchammas** [comment]
Fine with me. We use GraphFrames with 2.0.2 and are planning to upgrade to 2.1.1 this month.

**Comment by felixcheung** [comment]
Ok, I checked around. Probably much easier to maintain if only on 2.x release

**Comment by jkbradley** [comment]
OK thanks!  I'll send a PR soon

**Comment by felixcheung** [comment]
closed by #204
