### ISSUE TITLE
Slow connected component checkpoint interval test

### ISSUE THREAD

**Issue by phi-dbq** [graphframes/graphframes#194]
On a fairly recent MacBook Pro laptop and on the Travis CI, the [connected component check interval test](https://github.com/graphframes/graphframes/blob/master/src/test/scala/org/graphframes/lib/ConnectedComponentsSuite.scala#L161) takes very long time to finish.

- with `-Dspark.version=1.6.3 -Dscala.version=2.10.6`
  - checkpoint interval (9 minutes, 53 seconds)
- with `-Dspark.version=2.1.1 -Dscala.version=2.10.6`
  - checkpoint interval (3 minutes, 12 seconds)

These has caused CI to time-out for certain build variants. 
We should investigate this issue.

**Comment by phi-dbq** [comment]
Looks like this might be a side effect of the newly introduced fix for consistent integer ID for vertices.

**Comment by mengxr** [comment]
FYI, this is slow in 1.6 because there were some plan optimizer improvement in 2.0.

**Comment by mengxr** [comment]
Closing this after removing 1.6 support.
