### ISSUE TITLE
Update ConnectedComponent.symmetrize once we remove Spark 1.6 support

### ISSUE THREAD

**Issue by mengxr** [graphframes/graphframes#203]
The current implementation (https://github.com/graphframes/graphframes/blob/master/src/main/scala/org/graphframes/lib/ConnectedComponents.scala#L170) requires two passes over the edges, mainly to have the same code to support both Spark 1.6 and 2.x. Once we removed Spark 1.6 support (#193), we should optimize the implementation to speed-up CC.

**Comment by felixcheung** [comment]
closed by #205
