### ISSUE TITLE
Missing Python files in GraphFrames 0.5.0 jar

### ISSUE THREAD

**Issue by paulovn** [graphframes/graphframes#209]
The GraphFrames JAR for the 0.5.0 version seems to lack a couple of Python files that are in the source package:

    graphframes/lib/__init__.py
    graphframes/lib/aggregate_messages.py

As such, the `AggregateMessages` class is not available. Trying to load the Python examples also fails, since they contain an import 

    from graphframes.lib import AggregateMessages as AM

... which produces an exception.

I've tested the JAR as downloaded automatically by Spark (`graphframes_graphframes-0.5.0-spark2.1-s_2.11.jar`). I also downloaded manually a couple of other versions from the Maven repository and they seem to have all the same problem (I didn't check all of them).

Apparently, when building the jarfile the subdirectory `python/graphframes/lib` gets excluded.

**Comment by felixcheung** [comment]
This might be something we missed in the package description

**Comment by mengxr** [comment]
Thanks for reporting the bug! I think the root case is in the sbt-spark-pacage plugin we use: https://github.com/databricks/sbt-spark-package/blob/master/src/main/scala/sbtsparkpackage/SparkPackagePlugin.scala#L190. I will work on a fix soon.

**Comment by mengxr** [comment]
Sent a fix at https://github.com/databricks/sbt-spark-package/pull/34. Waiting for a new release of sbt-spark-package.

**Comment by mengxr** [comment]
@paulovn Please wait for the next release or build your own from master to fix the issue.

**Comment by paulovn** [comment]
ok, thanks for the fix!

**Comment by vnwarrior** [comment]
@paulovn sorry for commenting on an old bug - I build a the new assembly using "sbt assembly" . I got graphframes-assembly-0.6.0-SNAPSHOT-spark2.1.jar . 

How do I use this inside pyspark ? i tried pyfiles and jars, but constantly i keep getting "no module named graphframes". Should i copy the jar to some location or something ?

thanks!
