### ISSUE TITLE
[How to] use in pyspark using the assemby jar ?

### ISSUE THREAD

**Issue by thomasopsomer** [graphframes/graphframes#216]
Hi,

While working on some changes in graphframes, I'm wondering how do I need to use the assembly jar to use the python graphframes API ? When running `pyspark --jars <path to jar>`, it doesn't find the python bindings, how do I specify that ?

Thanks,
Thomas

**Comment by mengxr** [comment]
You also need to add the assembly jar to `--py-files`.

~~~bash
bin/pyspark --py-files /Users/meng/src/graphframes/target/scala-2.11/graphframes-assembly-0.6.0-SNAPSHOT-spark2.1.jar --jars /Users/meng/src/graphframes/target/scala-2.11/graphframes-assembly-0.6.0-SNAPSHOT-spark2.1.jar
~~~

**Comment by thomasopsomer** [comment]
Tks !
