### ISSUE TITLE
Cannot load graphframes in zeppelin

### ISSUE THREAD

**Issue by Swalloow** [graphframes/graphframes#218]
Hi, I tried to add graphframes as a spark package in my zeppelin interpreter.
But I get the following error:

```
Error setting properties for interpreter 'spark.spark': Could not find artifact 
graphframes:graphframes:jar:0.5.0-spark2.1-s_2.11 in central (http://repo1.maven.org/maven2/)
```

I tried to jar files but it also didn't work in pyspark. Same as following question.
[https://stackoverflow.com/questions/43357329/pyspark-importerror-no-module-named-graphframes-in-zeppelin-0-7-1-osx](url)

**Comment by felixcheung** [comment]
How did you add it? it looks like you are adding it as an artifact - try adding it as a spark package

**Comment by Swalloow** [comment]
@felixcheung Thanks! You're right. I adding it as an artifact.
So I added it to the $ SPARK_SUBMIT_OPTIONS environment variable in zeppelin-env.sh.
It works well.

**Comment by shafiquejamal** [comment]
@Swalloow Would you please show us exactly what you set `$SPARK_SUBMIT_OPTIONS` to? Thanks.

**Comment by siddhantsahu** [comment]
@shafiquejamal `export SPARK_SUBMIT_OPTIONS="--packages graphframes:graphframes:0.5.0-spark2.1-s_2.11"`
