### ISSUE TITLE
Connected Components Performance

### ISSUE THREAD

**Issue by brelloch** [graphframes/graphframes#226]
I am running on spark 2.1, graphframes 0.5 and AWS EMR with 3 r4.xlarge instances. When the generating the connected components for a graph of about 12 million edges it is taking around 3 hours. Is this the expected performance or are there way to tune things to improve it?

The code is below. I am fairly new to spark so any suggestions would be awesome.
```scala
def main(args: Array[String]): Unit = {
  val sparkConf = new SparkConf()
    .setMaster("yarn-cluster")
    .setAppName("Connected Component")

  val sc = new SparkContext(sparkConf)
  sc.setCheckpointDir("s3a://......")
  AWSUtils.setS3Credentials(sc.hadoopConfiguration)

  implicit val sqlContext = SQLContext.getOrCreate(sc)
  import sqlContext.implicits._

  val historical = sqlContext
    .read
    .option("mergeSchema", "false")
    .parquet("s3a://.....")
    .map(x => (x(0).toString, x(2).toString, x(1).toString, x(3).toString, x(4).toString.toLong, x(5).toString.toLong))

  // Complete graph
  val g = GraphFrame(
    historical.flatMap(e => List((e._1, e._3, e._5), (e._2, e._4, e._5))).toDF("id", "type", "timestamp"),
    historical.toDF("src", "dst", "srcType", "dstType", "timestamp", "companyId")
  )

  val connectedComponents: DataFrame = g.connectedComponents.run()

  connectedComponents.toDF().show(100, false)

  sc.stop()
}
```

**Comment by yun15** [comment]
Did you solve the question? I have this proble now. I use the GraphX to generate the connected components. And it is taking around 1.5 hours.

**Comment by brelloch** [comment]
I haven't look at this in a while but I believe a good portion of the problem was caused by using strings as the ids. I believe the strings are tied to ints within the processing so every time the id is needed it needs to look up the value in a separate object.

I ended up doing a scaled down version that didn't fully converge but was sufficient for our needs.
