### ISSUE TITLE
type GraphFrame not found 

### ISSUE THREAD

**Issue by asdspal** [graphframes/graphframes#229]
I'm getting following error while running a simple example from graphframes docs in notebook apache-toree scala kernel

Name: Compile Error
Message: <console>:18: error: not found: type GraphFrame
       val g: GraphFrame = examples.Graphs.friends
              ^
apache- spark version = 2.2
graphframes version = 0.5.0-spark2.1-s_2.11

**Comment by felixcheung** [comment]
you might need to check with the toree project on how it handles spark packages like graphframe..

**Comment by asdspal** [comment]
Hey, when I run "import org.graphframes.examples ", I don't get any error.
 Yes, I will check with toree project.

**Comment by felixcheung** [comment]
maybe you need to import `org.graphframes` first?

**Comment by asdspal** [comment]
Thanks, got it working after clearing the local maven and ivy caches.
