### ISSUE TITLE
pageRank return incorrect results within graphframe 0.4+ spark 2.2 combination

### ISSUE THREAD

**Issue by artem-aliev** [graphframes/graphframes#231]
the strange thing is: all graph frames version return the same result with spark 2.0
graph frame 0.3 return the same result with spark 2.2
so only latest graph frames and latest spark return different numbers.
I also checked with apache tinkerPop, that algorithm return the same results as spark 2.0
So it looks like an issue.

Here is a code I use to reproduce
```
import org.graphframes._
val g = examples.Graphs.friends
val results2 = g.pageRank.resetProbability(0.15).maxIter(10).run()
results2.vertices.select("id", "pagerank").orderBy("id").show()
```

Outputs:

spark-2.0.2-bin-hadoop2.7/./bin/spark-shell --packages graphframes:graphframes:$version

Spark 2.0.2 graphframes:graphframes:0.3.0-spark2.0-s_2.11
```
+---+-------------------+
| id|           pagerank|
+---+-------------------+
|  a|0.39143465933514154|
|  b|  1.842259190054981|
|  c|  1.877540087856477|
|  d|0.28427148788098855|
|  e|0.31616362485373634|
|  f|0.28427148788098855|
|  g|               0.15|
+---+-------------------+
```

Spark 2.0.2 graphframes:graphframes:0.4.0-spark2.0-s_2.11, time: 6934ms
```
+---+-------------------+
| id|           pagerank|
+---+-------------------+
|  a|0.39143465933514154|
|  b|  1.842259190054981|
|  c|  1.877540087856477|
|  d|0.28427148788098855|
|  e|0.31616362485373634|
|  f|0.28427148788098855|
|  g|               0.15|
+---+-------------------+
```
Spark 2.0.2 graphframes:graphframes:0.5.0-spark2.0-s_2.11, time: 87887ms
```
+---+-------------------+
| id|           pagerank|
+---+-------------------+
|  a|0.39143465933514154|
|  b|  1.842259190054981|
|  c|  1.877540087856477|
|  d|0.28427148788098855|
|  e|0.31616362485373634|
|  f|0.28427148788098855|
|  g|               0.15|
+---+-------------------+
```
spark-2.2.0-bin-hadoop2.7/./bin/spark-shell --packages graph frames:graph frames:$version

Spark 2.2 graphframes:graphframes:0.3.0-spark2.0-s_2.11
```
+---+-------------------+
| id|           pagerank|
+---+-------------------+
|  a|0.39143465933514154|
|  b|  1.842259190054981|
|  c|  1.877540087856477|
|  d|0.28427148788098855|
|  e|0.31616362485373634|
|  f|0.28427148788098855|
|  g|               0.15|
+---+-------------------+
```

Spark 2.2 graphframes:graphframes:0.4.0-spark2.0-s_2.11 time: 5809ms

```
+---+-------------------+
| id|           pagerank|
+---+-------------------+
|  a| 0.4485115093698443|
|  b| 2.7025217677349773|
|  c| 2.6667877057849627|
|  d|0.32504910549694244|
|  e| 0.3613490987992571|
|  f|0.32504910549694244|
|  g|0.17073170731707318|
+---+-------------------+
```
Spark 2.2 graphframes:graphframes:0.5.0-spark2.0-s_2.11, time: 70398ms

```
+---+-------------------+
| id|           pagerank|
+---+-------------------+
|  a| 0.4485115093698443|
|  b| 2.7025217677349773|
|  c| 2.6667877057849627|
|  d|0.32504910549694244|
|  e| 0.3613490987992571|
|  f|0.32504910549694244|
|  g|0.17073170731707318|
+---+—————————+
```

**Comment by artem-aliev** [comment]
Looks like not a problem but Spark 2.2 pageRank fixes:
SPARK-18845, SPARK-18847

graph frame 0.4 also dropped its own pageRank implementation and switch to spark one.
So these two fixes give that strange results.
The bug could be closed.

**Comment by felixcheung** [comment]
right, there are a few changes to pagerank in spark in 2.2
do you get a sense of whether the results are better though?

**Comment by artem-aliev** [comment]
The result is better. now it compatible with the wiki
Wiki: https://en.wikipedia.org/wiki/PageRank#Simplified_algorithm
> In the original form of PageRank, the sum of PageRank over all pages was the total number of pages on the web at that time

 I'll talk with tinkerPop guys, as the have the same issue.

**Comment by artem-aliev** [comment]
TinkerPop also fix this problem: https://issues.apache.org/jira/browse/TINKERPOP-1783
Close the issue.
