### ISSUE TITLE
Inaccurate PageRank docs

### ISSUE THREAD

**Issue by danielfx90** [graphframes/graphframes#233]
## **Current situation**
PageRank scala docs and user guide say that the implementation which runs for a fixed number of iterations (through the `maxIter` parameter) uses the Graphframes interface when in fact it uses the graphX's Pregel one.

## **What needs to be done?**
Both docs should match what the code does.

**Note:** I'll be creating a PR for this

**Comment by felixcheung** [comment]
fixed by 234
