### ISSUE TITLE
missing or invalid dependency detected while loading class file 'Logging.class'.

### ISSUE THREAD

**Issue by RayTsui** [graphframes/graphframes#239]
I use the following code to log in the cluster: 
spark-shell --master yarn --jars graphframes-0.5.0-spark2.1-s_2.11.jar scala-logging-slf4j_2.10-2.1.2.jar scala-logging-api_2.10-2.1.2.jar 

and run the follow spark code:

import org.apache.spark.SparkContext 
import org.apache.spark.sql.SparkSession 
import org.graphframes._

val ss = SparkSession.builder().appName("ECommerce Fraud Detection by Graph").config("spark.some.config.option", "some- value").config("spark.hadoop.validateOutputSpecs", "false").getOrCreate()  
val edges = ss.sql("select * from table")
val graphframes = GraphFrame.fromEdges(edges)

and error info occurs as follows:
rror: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term typesafe in package com,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access term scalalogging in value com.typesafe,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.typesafe.
error: missing or invalid dependency detected while loading class file 'Logging.class'.
Could not access type LazyLogging in value com.slf4j,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'Logging.class' was compiled against an incompatible version of com.slf4j.

Is there any solution to solve this, thanks a lot.

**Comment by felixcheung** [comment]
see #113 ?

**Comment by RayTsui** [comment]
Actually, as you see from above code, I did it as described in #113. But I suppose there still exists some inappropriate and problems or what I have done may be wrong, I use
spark-shell --master yarn --jars graphframes-0.5.0-spark2.1-s_2.11.jar scala-logging-slf4j_2.10-2.1.2.jar scala-logging-api_2.10-2.1.2.jar
to import the necessary jars and to execute my spark code. 

If you can find some wrong places, please figure it out. Thanks a lot.

**Comment by felixcheung** [comment]
What Scala version are you running with?

**Comment by RayTsui** [comment]
Actually, the exception has become #240.
