### ISSUE TITLE
Failed to parse bad motif string

### ISSUE THREAD

**Issue by geoHeil** [graphframes/graphframes#246]
How can I Implement something like neo4j's: `(a)-[e*..3]-(b)` with graphFrames?

- `(a)-[e]->(b); (b)-[e2]->(a)` will represent an undirected edge but  forces that there are actually vertices in both directions. Can I integrate an OR not just a AND into the Motif?

- `[e*..3]` will match 0,1,2,3 edges - would I need to use aggregate messages or iteratively looping over the possible values and `UNION`ing the results`

**Comment by felixcheung** [comment]
`(a)-[e]->(b); (b)-[e2]->(a)` is not undirected edge - it's actually vertices with 2 directed edges. If I recall, we don't really support undirected edges in GF. As for OR, I think you would need to `find()` twice and `unionAll` them.

it doesn't quite to it out of the box, there's a mention of match variable length at the end of this section http://graphframes.github.io/user-guide.html#motif-finding

**Comment by geoHeil** [comment]
Thanks for clarifying.
