### ISSUE TITLE
Connected components returning components with only one vertex

### ISSUE THREAD

**Issue by jzheng13** [graphframes/graphframes#272]
I was trying to run the `connectedComponents` function on my graph, but calling `id_component.groupBy('component').count()` showed that there are components with only one vertex mapped to them. Of course, a simple filter and join can sort out this issue but I think it'll be good to eliminate such cases in the first place.

I'm running the 0.5.0 version on Spark 2.2.

Thanks!

**Comment by rberenguel** [comment]
@jzheng13 a lone vertex is part of its own connected component. It's clear in the [equivalence relation definition in Wikipedia](https://en.wikipedia.org/wiki/Connected_component_(graph_theory)#An_equivalence_relation), but not so clear in the initial text blurb.

**Comment by felixcheung** [comment]
I haven't check, but I seems to recall a single vertex is also a "connected component" in the current implementation.

**Comment by jzheng13** [comment]
I just cannot really imagine a situation where it's useful to return a lone vertex, especially if that lone vertex is itself part of a "larger" connected component. It just seems like a waste of memory. But I'm cool with it.

**Comment by rberenguel** [comment]
@jzheng13 I don't follow your comment: if a vertex is part of a larger connected component, the algorithm will return it as part of the full component. If the lone vertex is part of its own connected component, it will just return it as part of itself as a component

**Comment by jzheng13** [comment]
@rberenguel My apologies. I realised that I didn't filter out my vertex list before including it in the graph, and that's why it's returning lone vertices. I assumed (wrongly) that it was returning lone vertices even though they should technically all be part of at least a 2-vertex component. I thought if it's not part of the distance matrix (the edges) it wouldn't be included at all, but I guess I was wrong.
