### ISSUE TITLE
Spark 2.4.x support?

### ISSUE THREAD

**Issue by chyh1990** [graphframes/graphframes#303]
please provide release package on Spark Packages.

**Comment by mengxr** [comment]
We are going to release 0.7 soon, which will support 2.4.

**Comment by mycaule** [comment]
Can you release for Scala 2.12 as well since Spark 2.4 supports Scala 2.12.

https://dl.bintray.com/spark-packages/maven/graphframes/graphframes

**Comment by mengxr** [comment]
That would be a separate request. We haven't tested Scala 2.12 support in 0.7.0. So we might wait for the next release.

**Comment by mlaferla** [comment]
can you please tell us when you plan to release an update which works with scala 2.12?
