### ISSUE TITLE
Plans for a release for Spark 2.4.x - scala 2.12?

### ISSUE THREAD

**Issue by emitc2h** [graphframes/graphframes#364]
Hello!

Is there a reason why there hasn't been a release for scala 2.12 and Spark 2.4.x? Is the support shifting to Spark 3 from now on? If such a release existed, I guarantee there would be interest!

Thanks,
Michel

**Comment by redsk** [comment]
It would be really great to have a release for scala 2.12 and spark 2.4!

**Comment by EnricoMi** [comment]
GraphFrames compiles against Spark 2.4 and Scala 2.12 out of the box. A 0.8.0 release would be so great and looks like a straightforward thing to do. @thunterdb @jkbradley @mengxr what are your thoughts on this?

**Comment by mengxr** [comment]
We don't have enough bandwidth to support both Spark 2.4 and 3.0 with cross Scala build in the master branch. Would making a 0.7.1 release with Spark 2.4 and Scala 2.11/2.12 meet your requirements?

**Comment by EnricoMi** [comment]
I am not asking to *support* Spark 2.4 with Scala 2.12. A one-off 0.8.0 release (from the tag) for Spark 2.4 with Scala 2.12 would suffice.

**Comment by mengxr** [comment]
I don't think feature-wise 0.8.0 is different from 0.7.1. But 0.8.0 code might not be compatible with Spark 2.4. So A one-off 0.7.1 release that is compatible with Scala 2.12 would suffice for you, right?

**Comment by EnricoMi** [comment]
Yes, the differences between 0.7.1 and 0.8.0 seem minimal. Though master and v0.8.0 tag builds fine for me against Spark 2.4.6 and Scala 2.12, 0.7.1 would be better than nothing. Cheers!

**Comment by mengxr** [comment]
Released 0.8.1 that is compatible with Spark 2.4 and Scala 2.12 at https://spark-packages.org/package/graphframes/graphframes. Note that it is not covered by CI and Scala 2.12 support is experimental in Spark 2.4. So this combination is considered as experimental.

**Comment by EnricoMi** [comment]
Works for me, thanks a lot!
