### ISSUE TITLE
Release for Spark 3.1 and 3.2

### ISSUE THREAD

**Issue by EnricoMi** [graphframes/graphframes#382]
GraphFrames 0.8.1 works well with Spark 3.1.1, so it would be great to have a Spark 3.1 release for it (see #381).

**Comment by EnricoMi** [comment]
@mengxr is releasing for Spark 3.1 on the agenda?

**Comment by EnricoMi** [comment]
Spark 3.2 is out and works perfectly well with Graphframes: #399.

**Comment by EnricoMi** [comment]
@mengxr thanks for the 0.8.2 release that targets Spark 3.1 and 3.2. When will the binaries land in the [spark-packages](https://mvnrepository.com/artifact/graphframes/graphframes?repo=spark-packages) Maven repository?

**Comment by machielg** [comment]
> @mengxr thanks for the 0.8.2 release that targets Spark 3.1 and 3.2. When will the binaries land in the [spark-packages](https://mvnrepository.com/artifact/graphframes/graphframes?repo=spark-packages) Maven repository?

@mengxr is there a step missing in the pipeline for deploying to mvn?
