### ISSUE TITLE
Since bintray repo is shutting down. Not able to download this jar.

### ISSUE THREAD

**Issue by skb81230** [graphframes/graphframes#384]
HI,

SInce bintray repo is down, i tried to add ICM repo. But still not able to downlad this jar. Can someone please help.

Could not resolve dependencies for project com.reltio:analytics:jar:2021.1-develop-SNAPSHOT: Could not find artifact graphframes:graphframes:jar:0.5.0.3-spark2.2 in icm (http://maven.icm.edu.pl/artifactory/repo/)

**Comment by mheilman** [comment]
bintray is going away on May 1, 2021, according to [this page](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

**Comment by skb81230** [comment]
Hi Michael,

Thanks for replying. Yes Bintray repo is shutting down.
Please help where we can find the graph frames jars ? Any other Repo?

**Comment by mheilman** [comment]
Sorry, I don't know where the package will be available after bintray goes down.

**Comment by skb81230** [comment]
Thank you for your response

**Comment by nvander1** [comment]
@jkbradley @thunterdb Any update on this? The sunset is coming soon, and the other brownout is today.

**Comment by DCameronMauch** [comment]
Yep, I am having the same issue.  Can't find a JAR for this online anywhere.

**Comment by nvander1** [comment]
What is the plan for this? Builds are failing now because the dependency can no longer be found

unresolved dependency: graphframes#graphframes;0.8.0-spark2.4-s_2.11: not found

**Comment by mengxr** [comment]
See http://apache-spark-user-list.1001560.n3.nabble.com/Bintray-replacement-for-spark-packages-org-td40128.html.

**Comment by DCameronMauch** [comment]
Why was this closed?  Was the issue resolved?

**Comment by bozhang2820** [comment]
As we have notified in the Apache Spark user list (see the link in @mengxr's previous comment), we have spun up a repository service at https://repos.spark-packages.org, and have migrated all existing artifacts (including those for graphframes) to the new repository service. 

Seems that @menglewis is working on fixing this issue in #385.

**Comment by carwilki** [comment]
getting this issue when trying to get get to the repo

```
$ curl -I https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark2.4-s_2.11/graphframes-0.8.1-spark2.4-s_2.11-sources.jar
HTTP/2 403 
content-type: application/xml
date: Wed, 28 Apr 2021 17:26:26 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 b005c06ee88e8a421caebec4b9f7d736.cloudfront.net (CloudFront)
x-amz-cf-pop: LAX50-C3
x-amz-cf-id: K_8XjOQ0Bag9sLsegZpd5IAqqqnTH0FRdQBtEQuTE2ceF8FTMRg_Hw==
```

**Comment by bozhang2820** [comment]
Hi @carwilki, publishing and consuming sources jars are not supported by spark-packages (not with Bintray either).

**Comment by carwilki** [comment]
hi @bozhang2820 i am running into the same issue with coursier + metals + sbt as well.

adding 
```
"Spark Packages Repo".at("https://repos.spark-packages.org/")
```
results in 
```
0m2021.04.27 18:12:19 INFO  [error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:ESC
[0m2021.04.27 18:12:19 INFO  [error] https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark2.4-s_2.11/graphframes-0.8.1-spark2.4-s_2.11-sources.jar: download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark2.4-s_2.11/graphframes-0.8.1-spark2.4-s_2.11-sources.jar (Server returned HTTP response code: 403 for URL: https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark2.4-s_2.11/graphframes-0.8.1-spark2.4-s_2.11-sources.jar) while downloading https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark2.4-s_2.11/graphframes-0.8.1-spark2.4-s_2.11-sources.jar
ESC[0m2021.04.27 18:12:19 INFO  [error]
```
if this is how this repo is intended to function, then is there an alternative hosting location that will allow for maven/ivy downloads? 

curious because I never ran into this issue with bintray.

**Comment by bozhang2820** [comment]
There is no sources jars on bintray either:
https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.8.1-spark2.4-s_2.11/

I'm wondering why coursier behaves differently (try to download the sources jar) with a change of the repository url.

**Comment by carwilki** [comment]
is https://repos.spark-packages.org/ not a maven repo?

**Comment by bozhang2820** [comment]
Maybe it is because the repository service returns 403 for files not found?

I just changed it to return 404 instead. Could you try your build again?
