### ISSUE TITLE
Artifact Download via Bintray fails with 403 Forbideen

### ISSUE THREAD

**Issue by dnltsk** [graphframes/graphframes#386]
Since today it is not possible to download the artifact from dl.bintray.com

The actual resource we try to get is
https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.4.0-spark2.0-s_2.11/graphframes-0.4.0-spark2.0-s_2.11.jar

Seems that all `spark-packages` are forbidden since today.
https://dl.bintray.com/spark-packages

**Comment by panthony** [comment]
I was able to fix the build of my project by replacing `https://dl.bintray.com/spark-packages` by `https://repos.spark-packages.org/` as suggested [here](https://github.com/graphframes/graphframes/pull/385/files/51c5b2b2267783552a44aae47bedc449d48a0073#r621743328)

**Comment by dnltsk** [comment]
Thanks for sharing this,
`/maven` needs to be replaced too. 
So https://repos.spark-packages.org/graphframes/graphframes/0.4.0-spark2.0-s_2.11/graphframes-0.4.0-spark2.0-s_2.11.jar seems to be correct.

**Comment by dnltsk** [comment]
Want to point out that Bintray seems to be somehow labeled as default Repository.
https://mvnrepository.com/repos/spark-packages

**Comment by dnltsk** [comment]
To finish this up, the new repository must be added to the Spark job configuration via
```
--repositories https://repos.spark-packages.org/
```

**Comment by dnltsk** [comment]
Might be linked to the issue I have/SparkPackages has
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
