### ISSUE TITLE
Spark libraries in maven not accessible

### ISSUE THREAD

**Issue by ricardoatsouza** [graphframes/graphframes#387]
Hello,

The spark [libraries of graphframes in Maven](https://mvnrepository.com/artifact/graphframes/graphframes?repo=spark-packages) are not available. Their access is returning `forbidden` ([example](https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.jar)). 

In this something you can check on your side?

Thanks in advance.

**Comment by ricardoatsouza** [comment]
Hello,

After quite some digging and seeing the PR #385 and issue #384, I came across with the fact that bintray was being shutdown ([article here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)).

Of course, took a bit until I realised about https://repos.spark-packages.org (explained in the issue [here](https://github.com/graphframes/graphframes/issues/384#issuecomment-828075353) and also in a post [here](http://apache-spark-user-list.1001560.n3.nabble.com/Bintray-replacement-for-spark-packages-org-td40128.html))

So, for whomever is still having this problem, assuming your `pom.xml` has the following lines:

```xml
        <repository>
            <id>bintray</id>
            <name>Bintray</name>
            <url>https://dl.bintray.com/spark-packages/maven/</url>
        </repository>
```

Simple replacing `https://dl.bintray.com/spark-packages/maven/` with `https://repos.spark-packages.org` should do the trick. :)

```xml
        <repository>
            <id>bintray</id>
            <name>Bintray</name>
            <url>https://repos.spark-packages.org</url>
        </repository>
```

Hope this helps others trying to solve the same issue.

**Comment by ricardoatsouza** [comment]
I closed the issue because I found a solution and hopefully others can refer to it. 
But the link in maven is still broken. If you have the means and time to fix it, that would be great. :)

**Comment by marzigolbaz** [comment]
@ricardoatsouza thanks for the info above. The project does not have a pom.xml file, did you create it on your own? Can you please share it with me over here? Also, since bintray is down, did you end up creating the jar file on your own? Can you please give more info? I'm very new to all these :) Thanks.

**Comment by ricardoatsouza** [comment]
@marzigolbaz Sure. I will try my best to explain.

A _pom_ file (Project Object Model, [see more](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html)) contains definitions about a certain project, like its configurations and dependencies. A _pom_ file (as you probably know) is part of Maven ([more information here](https://maven.apache.org/what-is-maven.html)). Apache Maven has tools to compile, build and publish a project.

This project does not have a _pom_ file. That is because this is a [Scala project](https://www.scala-lang.org/) and uses _sbt_ instead of Maven. Sbt ([link](https://www.scala-sbt.org/)) is quite a common tool when working with Scala. This repository has instead a [build.sbt](https://github.com/graphframes/graphframes/blob/master/build.sbt) file that specifies, pretty much, the same as a _pom_ file (i.e. the project, configurations and dependencies).

So, back to Maven (and different to _sbt_), the documentation also describes the [Maven Central Repository](https://maven.apache.org/repository/index.html), basically (roughly speaking) how a place in the internet can store and provide jar files (each jar file identifies by a _groupId_, an _artifactId_ and _version_).

There are dozens of places where a person or a company can publish _jar_ files for other to use, such as [Sonatype](https://search.maven.org/) and (guess) [bintray](https://bintray.com/). Basically, this project was publishing its releases to _bintray_ and, later, it got discontinued.

Then, back to the _pom_ file, how do you create one? If you are using [IntelliJ](https://www.jetbrains.com/idea/), it is surely possible to create [a Maven project in it](https://www.jetbrains.com/help/idea/maven-support.html). There is also some good information in this [official tutorial](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html).

Finally, how does my _pom_ file looks like? Roughly, like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.a-certain-group-id</groupId>
    <artifactId>my-project</artifactId>
    <version>0.0.1</version>

    <properties>
        <!-- a-few-properties -->
    </properties>

    <dependencies>
        
        <!-- other dependencies -->

        <dependency>
            <groupId>graphframes</groupId>
            <artifactId>graphframes</artifactId>
            <version>0.8.1-spark3.0-s_2.12</version>
        </dependency>

        <!-- other dependencies -->

    </dependencies>

    <repositories>
        <repository>
            <id>bintray</id>
            <name>Bintray Repository</name>
            <url>https://repos.spark-packages.org</url>
        </repository>
    </repositories>

</project>
```

I hope this helps. 👍

**Comment by marzigolbaz** [comment]
@ricardoatsouza thank you so much for your detailed description. Really appreciate your time :) It was very helpful!

**Comment by mhobby** [comment]
for anyone using Pyspark on AWS EMR and arriving here from a web search trying to resolve an unresolved dependency with graphframes, a quick fix can be found by downloading locally from repos.spark-packages.org, as per the OP's comment.

`> wget https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.jar`

then include the jar from local:
`> pyspark --jars /home/hadoop/graphframes-0.8.1-spark3.0-s_2.12.jar`

**Comment by gustave001** [comment]
how to deal with gradle ?

**Comment by saamarthgupta01** [comment]
@gustave001 may not help you, but hoping to help others wanting to adapt this onto gradle:
`repositories {
    repositories {
        mavenCentral()
        maven { url "https://repos.spark-packages.org" }
    }
}`
