### ISSUE TITLE
can not download 0.8.1-spark2.4-s_2.11.jar

### ISSUE THREAD

**Issue by sunseaxhj** [graphframes/graphframes#388]
all jars can not downlaod, my be download website have some problems, 
pls help!
![image](https://user-images.githubusercontent.com/44627075/118251117-c15e0780-b4d9-11eb-8270-0afa1dedefa8.png)

**Comment by marzigolbaz** [comment]
Same here. Cannot download any of the jars from this website: https://spark-packages.org/package/graphframes/graphframes - any help is appreciated.

**Comment by marzigolbaz** [comment]
@mengxr can you please help us?

**Comment by mengxr** [comment]
@bozhang2820 @gatorsmile We need to update Spark Packages website to use the new repo URLs.

@marzigolbaz Could you replace the URL with repos.spark-packages.org? For example:

https://repos.spark-packages.org/graphframes/graphframes/0.1.0-spark1.4/graphframes-0.1.0-spark1.4.jar

instead of

http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.1.0-spark1.4/graphframes-0.1.0-spark1.4.jar

**Comment by mengxr** [comment]
Leave the issue open until the Spark Package website is updated with the new URLs.

**Comment by marzigolbaz** [comment]
Thanks @mengxr for the quick turnaround :) what is the link to download the graphframes 0.8.1 for Spark 3.0.0? ([0.8.1-spark3.0-s_2.12](https://github.com/graphframes/graphframes/tree/b3b97cf1dac9e7be7806a938c8de406e5c09f431))?

**Comment by bozhang2820** [comment]
> Thanks @mengxr for the quick turnaround :) what is the link to download the graphframes 0.8.1 for Spark 3.0.0? ([0.8.1-spark3.0-s_2.12](https://github.com/graphframes/graphframes/tree/b3b97cf1dac9e7be7806a938c8de406e5c09f431))?

That would be: https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.jar

**Comment by bozhang2820** [comment]
The issue on spark-packages.org is now fixed.

**Comment by liangshi036** [comment]
so  how was the pom.xml file looks like to locate graphframes?

not from download link .

**Comment by KavyaKambi** [comment]
@mengxr We are using Bazel as our build tool. Trying to add GraphFrames to our dependency and getting below exception:

checksum errors: SHA-1: not found: https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.pom.sha1, MD5: not found: https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.pom.md5

When I try to open https://repos.spark-packages.org/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.pom.md5, it says "NoSuchKey" error. Can you please help us with this issue? This is blocking us in using GraphFrames.
