### ISSUE TITLE
Maven Repository?

### ISSUE THREAD

**Issue by anand-singh** [graphframes/graphframes#54]

**Comment by jkbradley** [comment]
Spark packages [http://spark-packages.org/package/graphframes/graphframes] has its own Maven repository.  Hopefully that works for you!

**Comment by shagunsodhani** [comment]
I did not get the "own Maven repository" part. Could you please elaborate?

**Comment by winstonewert** [comment]
@shagunsodhani  if you go to the above link, and click the [+] next to How To there are instructions for adding it to various build tools. Hopefully one of those applies, or you can adapt to yours.

**Comment by shagunsodhani** [comment]
Thanks a lot @winstonewert :+1:
