### ISSUE TITLE
Add aggregateMessages API to Python

### ISSUE THREAD

**Issue by jkbradley** [graphframes/graphframes#57]
It should mimic the Scala API and will likely need to be re-implemented in Python, following the Scala implementation.

**Comment by hughchristensen** [comment]
@thunterdb @jkbradley @qingpeng @mengxr @felixcheung @tsivula

**Comment by felixcheung** [comment]
I could help. Where are you at?

**Comment by tsivula** [comment]
Hello, I'm in Finland at GMT+2. I'll dive into this on Monday. It would be nice if I could consult you through some channel. Thank you in advance for any help.

**Comment by tsivula** [comment]
Hello @felixcheung, I just pushed my implementation proposition in [this commit](https://github.com/tsivula/graphframes/commit/dc9649fff1814a770f427556019fd11ce2863813). It would be nice if you could take a look at it.

I successfully tested it locally with a simple example:
```python
from graphframe import AggregateMessages as AM
from graphframes.examples import Graphs

g = Graphs(sqlContext).friends()  # Get example graph

df = g.aggregateMessages(
    pyspark.sql.functions.sum(AM.msg()),
    msgToDst=pyspark.sql.functions.lit(1))
```

**Comment by rogerthealien** [comment]
Hi,

I'm very interested in this as well. @tsivula I'm trying to test your implementation. Is it possible to use a UDF as an aggregation function?

**Comment by felixcheung** [comment]
@tsivula sorry about delay, I'm getting occupied this week and next.

I checked your commit, looking good! probably next would be to add some tests for it?

**Comment by tsivula** [comment]
Hello, I just created PR #169 for this.

**Comment by hughchristensen** [comment]
@thunterdb @jkbradley @qingpeng @mengxr @felixcheung Hi Guys. Can you help get this PR through please. We can not continue developing for this library until the PR has been accepted. 

Please can you do a best effort to get this done as we have dev resources waiting to go now. thank you!

**Comment by felixcheung** [comment]
As signed off previously, this looks good to me.

Sorry someone else would need to jump in to merge this.
