### ISSUE TITLE
Add cache(), persist() methods

### ISSUE THREAD

**Issue by jkbradley** [graphframes/graphframes#64]
They should just call cache() and persist() on both DataFrames.

**Comment by felixcheung** [comment]
btw, I'm having real problems with .cache() calls on DataFrames related to the graph.
This is what I have, simplified:
```
...
g = GraphFrame(v, e)
m = g.find("(a)-[]->(b)")
m.cache()
m.show()
```

This is probably unrelated to this issue specifically, but I find that if I have this `m.cache()` calls, it takes 2x-3x time for csv-backed edge/vertice DataFrames, and for Parquet-backed edge/vertice DataFrame, it just hangs.
I don't have a simple repro but I can try to recreate it.

**Comment by jkbradley** [comment]
That sounds bad.  It must be a DataFrames issue since GraphFrames isn't doing anything fancy (just joins).  A reproduction of it would be great, if possible, thanks!

**Comment by thunterdb** [comment]
Closing this ticket.
