### ISSUE TITLE
Scala documentation out of date

### ISSUE THREAD

**Issue by pmcb55** [graphframes/graphframes#71]
The Scala example seems a little out-of-date, as it calls the 'numIter()' method on PageRank, when in fact that method seems to be now called 'maxIter()', i.e. change this:

`val results = g.pageRank.resetProbability(0.01).numIter(20).run()`

...to this:

`val results = g.pageRank.resetProbability(0.01).maxIter(20).run()`

Also when running this example by cutting-and-pasting into 'spark-shell', I needed to manually import the GraphFrames class before instantiating 'g', i.e.:

`import org.graphframes.GraphFrame`

**Comment by jkbradley** [comment]
Thanks for reporting this; I'll push the updated docs soon.
