### ISSUE TITLE
Number of Connected Components

### ISSUE THREAD

**Issue by georgeha** [graphframes/graphframes#79]
Hello, 

how large can a Graphframe be in order to calculate its connected components? I need to scale for thousand of edges in very strong machines.

Thanks

**Comment by rxin** [comment]
You can definitely scale to billions of edges. Thanks.

**Comment by georgeha** [comment]
@rxin  I am trying to scale for  a few thousands of edges but I got java error

**Comment by jkbradley** [comment]
Can you give more info about your cluster, Spark setup, graph, code, etc.?

**Comment by peteb4ker** [comment]
I've also just run across this problem - please reopen this issue as its real.   I'm attempting to run connected components on a ~800 node graph, with the intention of scaling up from hundreds to millions of nodes.   Here's some info on my graph:

- simple digraph
- ~820 vertices
- ~858 edges

```
+--------+-----+
|inDegree|count|
+--------+-----+
|       1|  780|
|       2|   39|
+--------+-----+
```
Running connected components on this graph on a 32 cores 16GB single node never returns a result.  It eventually runs out of memory after creating hundreds of `reduce at VertexRDDImpl.scala:90` jobs with hundreds of thousands of reduce/mapPartition stages.    My dataframes look something like this:

```
+---------+- -+--+
|       id|  a| b|
+---------+---+--+
|233088|foo|10|
|233179|foo|10|
|595268|bar|10|
|26017|foo|10|
|592725|bar|10|
```

```
+-------------+---------+---------+
|           id|      src|      dst|
+-------------+---------+---------+
|-180166859|595268|233088|
| 175817470|233179|595268|
|-182283859|26017|592725|
| 172673170|592725|233179|
|-189204959|233088|233158|
```

Any ideas?  Let me know if you need any more info.

**Comment by jkbradley** [comment]
ConnectedComponents has quite a few ongoing problems.  We've been working on an improved implementation and hope to push it to GraphFrames master before long.

**Comment by nchammas** [comment]
@jkbradley - Are you tracking those improvements in a separate issue? Just curious if the improved implementation has already made it into 0.2.0 or master.

**Comment by jkbradley** [comment]
I just made an issue for it: https://github.com/graphframes/graphframes/issues/117

Not there yet, but as soon as we get the chance.

**Comment by nchammas** [comment]
Thanks @jkbradley.
