### ISSUE TITLE
How to use is with python3?

### ISSUE THREAD

**Issue by renewjoy** [graphframes/graphframes#85]
When I runt this import with pyspark with python3.51, it errors:

> from graphframes import *
> ZipImportError: can't find module 'graphframes'

but is success in pyspark with python 2.7.1

**Comment by mortada** [comment]
I'm running into the same issue

**Comment by thunterdb** [comment]
The current infrastructure of spark-packages publishes python bytecode (`.pyc` files) instead of source files. Since the package was prepared with python2, I believe this is the issue.

Unless you have some specific ways to address this issue (i.e. a pull request), I am going to wait for the next release of sbt-spark-packages which should alleviate the bytecode issue.

**Comment by nchammas** [comment]
@thunterdb - Can you expand on how this issue will be addressed by `sbt-spark-packages`? I'm curious.

By the way, the modern convention in Python for releasing artifacts is to publish [wheels](https://packaging.python.org/distributing/#wheels). Are there plans to use them?

**Comment by psinger** [comment]
Is there any news regarding this? Makes it impossible for me to use the package currently as Im running everything with python 3.

**Comment by nchammas** [comment]
@thunterdb - The latest [release of `sbt-spark-packages`](https://github.com/databricks/sbt-spark-package/releases) appears to be from August 15, a month after your latest comment. Is that release supposed to help fix this issue?

For the record, I'm also seeing that GraphFrames are broken on Python 3 as of Spark 2.0.0 / GraphFrames 0.2:

```
>>> print(spark.version)
2.0.0
>>> import sys
>>> print(sys.version)
3.5.2 (default, Sep 28 2016, 18:08:09) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
>>> from graphframes.examples import Graphs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
zipimport.ZipImportError: can't find module 'graphframes'
```

This works fine for me on Python 2.7.12.

Also, if someone wants to tackle the issue of Python 3 compatibility, where would they start? I can't seem to find documentation on how to build GraphFrames for Python.

**Comment by nchammas** [comment]
Looks like this has been addressed in a recent PR: #135

**Comment by thunterdb** [comment]
@renewjoy this issue is fixed in master, and a new release will be done soon. I am going to close this ticket.

**Comment by 8lenka8** [comment]
Hi,
Has this been addressed in 2016-11-12 release (Version: 0.3.0-spark2.0-s_2.11)? If not, can you let us know when it's planned for?
I've downloaded it today and am having the same issue on Python 3 but not on 2. Unfortunately, I need to use Python 3 because of something else.
Many thanks,
Elena

**Comment by thunterdb** [comment]
@8lenka8 it is fixed in the master branch, but I have not pushed an official update yet

**Comment by 8lenka8** [comment]
Thanks! I'm really looking forward to using graphframes in Python3. 

I have cloned the master branch and ran the build script. 
However, when I launch pyspark in terminal with package graphframes-assembly-0.4.0-SNAPSHOT-spark2.1.jar (from target folder - is this the right one to use? I copied it into spark's jars folder) I get the following error. 

$SPARK_HOME/bin/pyspark --packages graphframes:graphframes:0.4.0-spark2.1-s_2.11

UNRESOLVED DEPENDENCIES
not found

Do you have any pointers?

(apologies for asking questions, I'm not very experienced in this...)
