### ISSUE TITLE
Graphframes => Apache Spark 2.0 Compatible

### ISSUE THREAD

**Issue by anabranch** [graphframes/graphframes#91]
I'm playing around with getting this set up. It seems like there are some pretty significant code changes, not just remove `.map` on DataFrames.

Questions:
[ ] What framework should we use for logging internally since `org.apache.spark.Logging` no longer exists?

Tasks:
[ ] Fix LogInfo
[ ] Fix Logging
[ ] Fix `.map` calls
[ ] Fix `callUDF` calls.

**Comment by thunterdb** [comment]
@anabranch are you actively working on it? Otherwise I want to consolidate this ticket and #87 into #95 and work on it.
