### ISSUE TITLE
some problems when using graphframe API find()

### ISSUE THREAD

**Issue by summershenshen** [graphframes/graphframes#93]
When I use graphframes API find, I meet up with some problems. For example, graphframes g, var motif=g.find((a)-[e1]->(b);(a)-[e2]->(d);(c)-[e3]->(b);(c)-[e4]->(d)),I can get a dataframe as a result. But in the result vertex a and vertex c may be the same, if I want all the vertexes which have different names are different vertexes,except I can use motif=motif.filter("XXX"),what other methods can I use?

**Comment by thunterdb** [comment]
@summershenshen I am sorry I having a hard time to understand your issue. Can you give a code example with some data or a gist? That would clarify the issue.

Thank you in advance.

**Comment by thunterdb** [comment]
@summershenshen are you still experiencing this issue? Otherwise I will close this ticket.

**Comment by summershenshen** [comment]
OK. This ticket can be closed.


--

Shen Wang
Master Degree Candidate
Department of Computer Science and Technology
Nanjing University
Nanjing,China,210023
Phone: +86 15996311418
Email: wangshen0716@163.com

At 2016-08-17 02:30:12, "Timothy Hunter" <notifications@github.com> wrote:


@summershenshen are you still experiencing this issue? Otherwise I will close this ticket.
