### ISSUE TITLE
Mistake in Documentation 

### ISSUE THREAD

**Issue by nadav-grossaug** [graphframes/graphframes#94]
in http://graphframes.github.io/api/python/graphframes.html#graphframes.GraphFrame

Documentation states:

connectedComponents()
Computes the connected components of the graph.

See Scala documentation for more details.

Returns:	GraphFrame with new vertices column “component”

**should be:**  Returns: DataFrame with new vertices column “component” (as is in Scala)

**Comment by rxin** [comment]
Can you submit a pull request?

**Comment by felixcheung** [comment]
This should have been fixed already in #37
