### ISSUE TITLE
Publish graphframes for Spark 2.0

### ISSUE THREAD

**Issue by thunterdb** [graphframes/graphframes#95]
GraphFrames will be published for Spark 2.0. This will be the first version that officially supports scala 2.10 and scala 2.11 .

**Comment by jmontess** [comment]
Hello,

I was wondering if there is a planned date for this. I'm migrating form spark 1.6 to 2.0.

Thanks in advance,
J.

**Comment by thunterdb** [comment]
@jmontess I will not have the time to work on this issue for the next week. @felixcheung might be able to take a look at it before. Of course, feel free to submit a patch if you want.

**Comment by felixcheung** [comment]
I can look hopefully today. Feel free to check it out if you get a chance, @jmontess

**Comment by dlawre14** [comment]
Is there any word on the state of Python support for Spark 2.0 and GraphFrames?

**Comment by felixcheung** [comment]
WIP #99

**Comment by jmontess** [comment]
Thanks @felixcheung. I will check it out now...

**Comment by thunterdb** [comment]
The new binaries have been pushed: https://spark-packages.org/package/graphframes/graphframes
